server:
  port: 7002
# Eureka。
eureka:
  instance:
    hostname: eureka7002.com # Eureka 服务端的实例名字。
  client:
    register-with-eureka: false # 是否向 Eureka 注册中心注册。（服务端不用注册自己）。
    fetch-registry: false # 不去服务端拿注册信息。表示自己为注册中心。
    service-url: # 监控页面。
      # 单机。
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");

      # 集群。
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7003.com:7003/eureka
