server:
  port: 8002
mybatis:
  type-aliases-package: com.geek.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源。
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.142.143:3307/db02?characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-privider-dept8002 # 修改 Eureka 默认描述信息。
